mapapptestenv:
  extends:
    file: docker-compose-common.yml
    service: mapapp
  ports:
    - "22"
    - "80"
    - "3306"
    - "18900"
    - "18901"
    - "9001"
  volumes:
    - ~/MAP_Regression_Results:/home/MAP_Regression_Results
    - ~/server_logs:/var/log
  volumes_from:
    - mysqldatavoltestenv
    - ftpdatavoltestenv
  links:
    - etcdapptestenv:etcd

ftpapptestenv:
  extends:
    file: docker-compose-common.yml
    service: ftpapp
  ports:
    - "21"
  volumes_from:
    - ftpdatavoltestenv

mysqldatavoltestenv:
  extends:
    file: docker-compose-common.yml
    service: mysqldatavol

ftpdatavoltestenv:
  extends:
    file: docker-compose-common.yml
    service: ftpdatavol

etcdapptestenv:
  image: quay.io/coreos/etcd:v0.4.6
