mapapp:
  image: quay.io/iseexchange/tacstack:latest
  command: supervisord -n
  environment:
    - MAP_PRODUCTION=false
    - PYTHONPATH=/home/robotframework
  restart: always

ftpapp:
  image: jumanjiman/dropbox
  restart: always

mysqldatavol:
  image: quay.io/iseexchange/tacstack_mysqldata:latest

ftpdatavol:
  image: quay.io/iseexchange/tacstack_ftpdata:latest
