mapapp:
  image: quay.io/iseexchange/tacstack:latest
  command: supervisord -n
  environment:
    - MAP_PRODUCTION=false

ftpapp:
  image: jumanjiman/dropbox

mysqldatavol:
  image: quay.io/iseexchange/tacstack_mysqldata:latest

ftpdatavol:
  image: quay.io/iseexchange/tacstack_ftpdata:latest
